CREATE FUNCTION dbo.sfn_EBCDIC_2ASCII 
              ( @input char(2) )      
RETURNS char(1)
AS
BEGIN
    DECLARE @ResultVar char(1)

    SELECT @ResultVar =

    CASE

    WHEN @input = '00'   THEN ''     --  row:  0  NUL // Null
    WHEN @input = '01'   THEN ''     --  row:  1  SOH // Start of heading
    WHEN @input = '02'   THEN ''     --  row:  2  STX // Start of text
    WHEN @input = '03'   THEN ''     --  row:  3  ETX // End of text
    WHEN @input = '04'   THEN ''     --  row:  4  SEL // Select
    WHEN @input = '05'   THEN ''     --  row:  5  HT  // Horizontal tab
    WHEN @input = '06'   THEN ''     --  row:  6  RNL // Required new line
    WHEN @input = '07'   THEN ''     --  row:  7  DEL // Delete
    WHEN @input = '08'   THEN ''     --  row:  8  GE  // Graphic escape
    WHEN @input = '09'   THEN ''     --  row:  9  SPS // Superscript
    WHEN @input = '0A'   THEN ''     --  row: 10  RPT // Repeat
    WHEN @input = '0B'   THEN ''     --  row: 11  VT  // Vertical tab
    WHEN @input = '0C'   THEN ''     --  row: 12  FF  // 
    WHEN @input = '0D'   THEN ''     --  row: 13  CR  // Carriage return
    WHEN @input = '0E'   THEN ''     --  row: 14  SO  // Shift out
    WHEN @input = '0F'   THEN ''     --  row: 15  SI  // Shift in
    WHEN @input = '10'   THEN ''     --  row: 16  DLE // Data length escape
    WHEN @input = '11'   THEN ''     --  row: 17  DC1 // Device control 1
    WHEN @input = '12'   THEN ''     --  row: 18  DC2 // Device control 2
    WHEN @input = '13'   THEN ''     --  row: 19  DC3 // Device control 3
    WHEN @input = '14'   THEN ''     --  row: 20  RES/ENP // Restore/enable presentation
    WHEN @input = '15'   THEN ''     --  row: 21  NL  // New line
    WHEN @input = '16'   THEN ''     --  row: 22  BS  // Backspace
    WHEN @input = '17'   THEN ''     --  row: 23  POC // Program-operator communication
    WHEN @input = '18'   THEN ''     --  row: 24  CAN // Cancel
    WHEN @input = '19'   THEN ''     --  row: 25  EM  // End of medium
    WHEN @input = '1A'   THEN ''     --  row: 26  UBS // Unit backspace
    WHEN @input = '1B'   THEN ''     --  row: 27  CU1 // Customer use 1
    WHEN @input = '1C'   THEN ''     --  row: 28  IFS // Interchange file separator
    WHEN @input = '1D'   THEN ''     --  row: 29  IGS // Interchange group separator
    WHEN @input = '1E'   THEN ''     --  row: 30  IRS // Interchange record separator
    WHEN @input = '1F'   THEN ''     --  row: 31  IUS/ITB // Interchange unit separator/intermediate transmission block
    WHEN @input = '20'   THEN ''     --  row: 32  DS  // Digit select
    WHEN @input = '21'   THEN ''     --  row: 33  SOS // Start of significance
    WHEN @input = '22'   THEN ''     --  row: 34  FS  // Field separator
    WHEN @input = '23'   THEN ''     --  row: 35  WUS // Word underscore
    WHEN @input = '24'   THEN ''     --  row: 36  BYP/INP // Bypass/inhibit presentation
    WHEN @input = '25'   THEN ''     --  row: 37  LF  // Line Feed
    WHEN @input = '26'   THEN ''     --  row: 38  ETB // End of Transmission Block
    WHEN @input = '27'   THEN ''     --  row: 39  ESC // Escape
    WHEN @input = '28'   THEN ''     --  row: 40  SA  // Set Attribute
    WHEN @input = '29'   THEN ''     --  row: 41  SFE // Start Field Extended
    WHEN @input = '2A'   THEN ''     --  row: 42  SM/SW // Set Mode/ Set Switch
    WHEN @input = '2B'   THEN ''     --  row: 43  CSP // Control Sequence Prefix
    WHEN @input = '2C'   THEN ''     --  row: 44  MFA // Modify Field Attribute
    WHEN @input = '2D'   THEN ''     --  row: 45  ENQ // Enquiry
    WHEN @input = '2E'   THEN ''     --  row: 46  ACK // Acknowledge
    WHEN @input = '2F'   THEN ''     --  row: 47  BEL // Bell
    WHEN @input = '30'   THEN ''     --  row: 48      // Nicht belegt
    WHEN @input = '31'   THEN ''     --  row: 49      // Nicht belegt
    WHEN @input = '32'   THEN ''     --  row: 50  SYN // Synchronous idle
    WHEN @input = '33'   THEN ''     --  row: 51  IRS // Index return
    WHEN @input = '34'   THEN ''     --  row: 52  PP  // Presentation position
    WHEN @input = '35'   THEN ''     --  row: 53  TRN // Transparent
    WHEN @input = '36'   THEN ''     --  row: 54  NBS // Numeric backspace
    WHEN @input = '37'   THEN ''     --  row: 55  EOT // End of transmission
    WHEN @input = '38'   THEN ''     --  row: 56  SBS // Subscript
    WHEN @input = '39'   THEN ''     --  row: 57  IT  // Indent tab
    WHEN @input = '3A'   THEN ''     --  row: 58  RFF // Required form feed
    WHEN @input = '3B'   THEN ''     --  row: 59  CU3 // Customer use 3
    WHEN @input = '3C'   THEN ''     --  row: 60  DC4 // Device control 4
    WHEN @input = '3D'   THEN ''     --  row: 61  NAK // Negative Acknowledge
    WHEN @input = '3E'   THEN ''     --  row: 62  SUB // Substitute
    WHEN @input = '3F'   THEN ''     --  row: 63  SP  // Space
    WHEN @input = '40'   THEN ''     --  row: 64  RSP // Required space
    WHEN @input = '41'   THEN ''     --  row: 65      // Nicht belegt
    WHEN @input = '42'   THEN ''     --  row: 66      // Nicht belegt
    WHEN @input = '43'   THEN ''     --  row: 67      // Nicht belegt
    WHEN @input = '44'   THEN ''     --  row: 68      // Nicht belegt
    WHEN @input = '45'   THEN ''     --  row: 69      // Nicht belegt
    WHEN @input = '46'   THEN ''     --  row: 70      // Nicht belegt
    WHEN @input = '47'   THEN ''     --  row: 71      // Nicht belegt
    WHEN @input = '48'   THEN ''     --  row: 72      // Nicht belegt
    WHEN @input = '49'   THEN ''     --  row: 73      // Nicht belegt
    WHEN @input = '4A'   THEN '¢'    --  row: 74      // Cent-Sign
    WHEN @input = '4B'   THEN '.'    --  row: 75      // Full Stop
    WHEN @input = '4C'   THEN '<'    --  row: 76      // Less than
    WHEN @input = '4D'   THEN '('    --  row: 77      // Left bracket
    WHEN @input = '4E'   THEN '+'    --  row: 78      // Plus
    WHEN @input = '4F'   THEN '|'    --  row: 79      // Logical OR
    WHEN @input = '50'   THEN '&'    --  row: 80      // Ampersand
    WHEN @input = '51'   THEN ''     --  row: 81      // Nicht belegt
    WHEN @input = '52'   THEN ''     --  row: 82      // Nicht belegt
    WHEN @input = '53'   THEN ''     --  row: 83      // Nicht belegt
    WHEN @input = '54'   THEN ''     --  row: 84      // Nicht belegt
    WHEN @input = '55'   THEN ''     --  row: 85      // Nicht belegt
    WHEN @input = '56'   THEN ''     --  row: 86      // Nicht belegt
    WHEN @input = '57'   THEN ''     --  row: 87      // Nicht belegt
    WHEN @input = '58'   THEN ''     --  row: 88      // Nicht belegt
    WHEN @input = '59'   THEN ''     --  row: 89      // Nicht belegt
    WHEN @input = '5A'   THEN '!'    --  row: 90      // Exclamation Mark
    WHEN @input = '5B'   THEN '$'    --  row: 91      // Dollar sign
    WHEN @input = '5C'   THEN '*'    --  row: 92      // Asterisk
    WHEN @input = '5D'   THEN ')'    --  row: 93      // Right bracket
    WHEN @input = '5E'   THEN ';'    --  row: 94      // Semicolon
    WHEN @input = '5F'   THEN '¬'    --  row: 95      // Logical NOT
    WHEN @input = '60'   THEN '-'    --  row: 96      // Hyphen
    WHEN @input = '61'   THEN '/'    --  row: 97      // Slash
    WHEN @input = '62'   THEN ''     --  row: 98      // Nicht belegt
    WHEN @input = '63'   THEN ''     --  row: 99      // Nicht belegt
    WHEN @input = '64'   THEN ''     --  row:100      // Nicht belegt
    WHEN @input = '65'   THEN ''     --  row:101      // Nicht belegt
    WHEN @input = '66'   THEN ''     --  row:102      // Nicht belegt
    WHEN @input = '67'   THEN ''     --  row:103      // Nicht belegt
    WHEN @input = '68'   THEN ''     --  row:104      // Nicht belegt
    WHEN @input = '69'   THEN ''     --  row:105      // Nicht belegt
    WHEN @input = '6A'   THEN '¦'    --  row:106      // Broken pipe; Broken Bar
    WHEN @input = '6B'   THEN ','    --  row:107      // Comma
    WHEN @input = '6C'   THEN '%'    --  row:108      // Percent
    WHEN @input = '6D'   THEN '_'    --  row:109      // Underscore
    WHEN @input = '6E'   THEN '>'    --  row:110      // Greater than
    WHEN @input = '6F'   THEN '?'    --  row:111      // Question mark
    WHEN @input = '70'   THEN ''     --  row:112      // Nicht belegt
    WHEN @input = '71'   THEN ''     --  row:113      // Nicht belegt
    WHEN @input = '72'   THEN ''     --  row:114      // Nicht belegt
    WHEN @input = '73'   THEN ''     --  row:115      // Nicht belegt
    WHEN @input = '74'   THEN ''     --  row:116      // Nicht belegt
    WHEN @input = '75'   THEN ''     --  row:117      // Nicht belegt
    WHEN @input = '76'   THEN ''     --  row:118      // Nicht belegt
    WHEN @input = '77'   THEN ''     --  row:119      // Nicht belegt
    WHEN @input = '78'   THEN ''     --  row:120      // Nicht belegt
    WHEN @input = '79'   THEN '`'    --  row:121      // Grave accent
    WHEN @input = '7A'   THEN ':'    --  row:122      // Doppelpunkt
    WHEN @input = '7B'   THEN '#'    --  row:123      // number sign, mesh, pound, carpet, sharp
    WHEN @input = '7C'   THEN '@'    --  row:124      // at sign
    WHEN @input = '7D'   THEN ''''   --  row:125      // Apostroph, single quot
    WHEN @input = '7E'   THEN '='    --  row:126      // Equals to
    WHEN @input = '7F'   THEN '"'    --  row:127      // Quotes
    WHEN @input = '80'   THEN ''     --  row:128      // Nicht belegt
    WHEN @input = '81'   THEN 'a'    --  row:129      // Kleines a
    WHEN @input = '82'   THEN 'b'    --  row:130      // Kleines b
    WHEN @input = '83'   THEN 'c'    --  row:131      // Kleines c
    WHEN @input = '84'   THEN 'd'    --  row:132      // Kleines d
    WHEN @input = '85'   THEN 'e'    --  row:133      // Kleines e
    WHEN @input = '86'   THEN 'f'    --  row:134      // Kleines f
    WHEN @input = '87'   THEN 'g'    --  row:135      // Kleines g
    WHEN @input = '88'   THEN 'h'    --  row:136      // Kleines h
    WHEN @input = '89'   THEN 'i'    --  row:137      // Kleines i
    WHEN @input = '8A'   THEN ''     --  row:138      // Nicht belegt
    WHEN @input = '8B'   THEN ''     --  row:139      // Nicht belegt
    WHEN @input = '8C'   THEN ''     --  row:140      // Nicht belegt
    WHEN @input = '8D'   THEN ''     --  row:141      // Nicht belegt
    WHEN @input = '8E'   THEN ''     --  row:142      // Nicht belegt
    WHEN @input = '8F'   THEN ''     --  row:143      // Nicht belegt
    WHEN @input = '90'   THEN ''     --  row:144      // Nicht belegt
    WHEN @input = '91'   THEN 'j'    --  row:145      // Kleines j
    WHEN @input = '92'   THEN 'k'    --  row:146      // Kleines k
    WHEN @input = '93'   THEN 'l'    --  row:147      // Kleines l
    WHEN @input = '94'   THEN 'm'    --  row:148      // Kleines m
    WHEN @input = '95'   THEN 'n'    --  row:149      // Kleines n
    WHEN @input = '96'   THEN 'o'    --  row:150      // Kleines o
    WHEN @input = '97'   THEN 'p'    --  row:151      // Kleines p
    WHEN @input = '98'   THEN 'q'    --  row:152      // Kleines q
    WHEN @input = '99'   THEN 'r'    --  row:153      // Kleines r
    WHEN @input = '9A'   THEN ''     --  row:154      // Nicht belegt
    WHEN @input = '9B'   THEN ''     --  row:155      // Nicht belegt
    WHEN @input = '9C'   THEN ''     --  row:156      // Nicht belegt
    WHEN @input = '9D'   THEN ''     --  row:157      // Nicht belegt
    WHEN @input = '9E'   THEN ''     --  row:158      // Nicht belegt
    WHEN @input = '9F'   THEN ''     --  row:159      // Nicht belegt
    WHEN @input = 'A0'   THEN ''     --  row:160      // Nicht belegt
    WHEN @input = 'A1'   THEN '~'    --  row:161      // Tilde
    WHEN @input = 'A2'   THEN 's'    --  row:162      // Kleines s
    WHEN @input = 'A3'   THEN 't'    --  row:163      // Kleines t
    WHEN @input = 'A4'   THEN 'u'    --  row:164      // Kleines u
    WHEN @input = 'A5'   THEN 'v'    --  row:165      // Kleines v
    WHEN @input = 'A6'   THEN 'w'    --  row:166      // Kleines w
    WHEN @input = 'A7'   THEN 'x'    --  row:167      // Kleines x
    WHEN @input = 'A8'   THEN 'y'    --  row:168      // Kleines y
    WHEN @input = 'A9'   THEN 'z'    --  row:169      // Kleines z
    WHEN @input = 'AA'   THEN ''     --  row:170      // Nicht belegt
    WHEN @input = 'AB'   THEN ''     --  row:171      // Nicht belegt
    WHEN @input = 'AC'   THEN ''     --  row:172      // Nicht belegt
    WHEN @input = 'AD'   THEN ''     --  row:173      // Nicht belegt
    WHEN @input = 'AE'   THEN ''     --  row:174      // Nicht belegt
    WHEN @input = 'AF'   THEN ''     --  row:175      // Nicht belegt
    WHEN @input = 'B0'   THEN ''     --  row:176      // Nicht belegt
    WHEN @input = 'B1'   THEN ''     --  row:177      // Nicht belegt
    WHEN @input = 'B2'   THEN ''     --  row:178      // Nicht belegt
    WHEN @input = 'B3'   THEN ''     --  row:179      // Nicht belegt
    WHEN @input = 'B4'   THEN ''     --  row:180      // Nicht belegt
    WHEN @input = 'B5'   THEN ''     --  row:181      // Nicht belegt
    WHEN @input = 'B6'   THEN ''     --  row:182      // Nicht belegt
    WHEN @input = 'B7'   THEN ''     --  row:183      // Nicht belegt
    WHEN @input = 'B8'   THEN ''     --  row:184      // Nicht belegt
    WHEN @input = 'B9'   THEN ''     --  row:185      // Nicht belegt
    WHEN @input = 'BA'   THEN ''     --  row:186      // Nicht belegt
    WHEN @input = 'BB'   THEN ''     --  row:187      // Nicht belegt
    WHEN @input = 'BC'   THEN ''     --  row:188      // Nicht belegt
    WHEN @input = 'BD'   THEN ''     --  row:189      // Nicht belegt
    WHEN @input = 'BE'   THEN ''     --  row:190      // Nicht belegt
    WHEN @input = 'BF'   THEN ''     --  row:191      // Nicht belegt
    WHEN @input = 'C0'   THEN '{'    --  row:192      // Opening brace
    WHEN @input = 'C1'   THEN 'A'    --  row:193      // Großes A
    WHEN @input = 'C2'   THEN 'B'    --  row:194      // Großes B
    WHEN @input = 'C3'   THEN 'C'    --  row:195      // Großes C
    WHEN @input = 'C4'   THEN 'D'    --  row:196      // Großes D
    WHEN @input = 'C5'   THEN 'E'    --  row:197      // Großes E
    WHEN @input = 'C6'   THEN 'F'    --  row:198      // Großes F
    WHEN @input = 'C7'   THEN 'G'    --  row:199      // Großes G
    WHEN @input = 'C8'   THEN 'H'    --  row:200      // Großes H
    WHEN @input = 'C9'   THEN 'I'    --  row:201      // Großes I
    WHEN @input = 'CA'   THEN '­'    --  row:202  SHY // Syllable hyphen (Shy)
    WHEN @input = 'CB'   THEN ''     --  row:203      // Nicht belegt
    WHEN @input = 'CC'   THEN ''     --  row:204      // Nicht belegt
    WHEN @input = 'CD'   THEN ''     --  row:205      // Nicht belegt
    WHEN @input = 'CE'   THEN ''     --  row:206      // Nicht belegt
    WHEN @input = 'CF'   THEN ''     --  row:207      // Nicht belegt
    WHEN @input = 'D0'   THEN '}'    --  row:208      // Closing brace
    WHEN @input = 'D1'   THEN 'J'    --  row:209      // Großes J
    WHEN @input = 'D2'   THEN 'K'    --  row:210      // Großes K
    WHEN @input = 'D3'   THEN 'L'    --  row:211      // Großes L
    WHEN @input = 'D4'   THEN 'M'    --  row:212      // Großes M
    WHEN @input = 'D5'   THEN 'N'    --  row:213      // Großes N
    WHEN @input = 'D6'   THEN 'O'    --  row:214      // Großes O
    WHEN @input = 'D7'   THEN 'P'    --  row:215      // Großes P
    WHEN @input = 'D8'   THEN 'Q'    --  row:216      // Großes Q
    WHEN @input = 'D9'   THEN 'R'    --  row:217      // Großes R
    WHEN @input = 'DA'   THEN ''     --  row:218      // Nicht belegt
    WHEN @input = 'DB'   THEN ''     --  row:219      // Nicht belegt
    WHEN @input = 'DC'   THEN ''     --  row:220      // Nicht belegt
    WHEN @input = 'DD'   THEN ''     --  row:221      // Nicht belegt
    WHEN @input = 'DE'   THEN ''     --  row:222      // Nicht belegt
    WHEN @input = 'DF'   THEN ''     --  row:223      // Nicht belegt
    WHEN @input = 'E0'   THEN '\'    --  row:224      // Reverse slash, Backslash
    WHEN @input = 'E1'   THEN ''     --  row:225  NSP // Numeric space
    WHEN @input = 'E2'   THEN 'S'    --  row:226      // Großes S
    WHEN @input = 'E3'   THEN 'T'    --  row:227      // Großes T
    WHEN @input = 'E4'   THEN 'U'    --  row:228      // Großes U
    WHEN @input = 'E5'   THEN 'V'    --  row:229      // Großes V
    WHEN @input = 'E6'   THEN 'W'    --  row:230      // Großes W
    WHEN @input = 'E7'   THEN 'X'    --  row:231      // Großes X
    WHEN @input = 'E8'   THEN 'Y'    --  row:232      // Großes Y
    WHEN @input = 'E9'   THEN 'Z'    --  row:233      // Großes Z
    WHEN @input = 'EA'   THEN ''     --  row:234      // Nicht belegt
    WHEN @input = 'EB'   THEN ''     --  row:235      // Nicht belegt
    WHEN @input = 'EC'   THEN ''     --  row:236      // Nicht belegt
    WHEN @input = 'ED'   THEN ''     --  row:237      // Nicht belegt
    WHEN @input = 'EE'   THEN ''     --  row:238      // Nicht belegt
    WHEN @input = 'EF'   THEN ''     --  row:239      // Nicht belegt
    WHEN @input = 'F0'   THEN '0'    --  row:240      // Ziffer 0
    WHEN @input = 'F1'   THEN '1'    --  row:241      // Ziffer 1
    WHEN @input = 'F2'   THEN '2'    --  row:242      // Ziffer 2
    WHEN @input = 'F3'   THEN '3'    --  row:243      // Ziffer 3
    WHEN @input = 'F4'   THEN '4'    --  row:244      // Ziffer 4
    WHEN @input = 'F5'   THEN '5'    --  row:245      // Ziffer 5
    WHEN @input = 'F6'   THEN '6'    --  row:246      // Ziffer 6
    WHEN @input = 'F7'   THEN '7'    --  row:247      // Ziffer 7
    WHEN @input = 'F8'   THEN '8'    --  row:248      // Ziffer 8
    WHEN @input = 'F9'   THEN '9'    --  row:249      // Ziffer 9
    WHEN @input = 'FA'   THEN ''     --  row:250      // Nicht belegt
    WHEN @input = 'FB'   THEN ''     --  row:251      // Nicht belegt
    WHEN @input = 'FC'   THEN ''     --  row:252      // Nicht belegt
    WHEN @input = 'FD'   THEN ''     --  row:253      // Nicht belegt
    WHEN @input = 'FE'   THEN ''     --  row:254      // Nicht belegt
    WHEN @input = 'FF'   THEN ''     --  row:255  EO  // Eight ones
    ELSE                      NULL                                 
    
    END  -- end CASE

    -- Return 
    RETURN @ResultVar

END  -- end FUNCTION

